In [131]:
gravity=[7,4,2,0,0,6,0,7,0]

import numpy as np

arr = np.zeros((8, 9))

arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [111]:
arr[1:,0] = 1
arr[4:,1] = 1
arr[6:,2] = 1
arr[2:,5] = 1
arr[1:,7] = 1

arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 1., 0., 1., 0.],
       [1., 0., 0., 0., 0., 1., 0., 1., 0.],
       [1., 1., 0., 0., 0., 1., 0., 1., 0.],
       [1., 1., 0., 0., 0., 1., 0., 1., 0.],
       [1., 1., 1., 0., 0., 1., 0., 1., 0.],
       [1., 1., 1., 0., 0., 1., 0., 1., 0.]])

In [133]:
for i in gravity:
    for j in range(len(gravity)):
        if i != 0:
            arr[8-i:,j] = 1
            
        
#arr[1:,0] = 1
#arr[4:,1] = 1
#arr[6:,2] = 1
#arr[2:,5] = 1
#arr[1:,7] = 1

arr

SyntaxError: 'return' outside function (1141315408.py, line 5)

In [85]:
list(arr[0]).count(0)

7

In [122]:
gravity=[7,4,2,0,0,6,0,7,0]
max_cnt=0

In [123]:
for i in range(len(gravity)-1): # i = 0~7
    cnt=0
    for j in range(i+1, len(gravity)): # i+!~8
        if gravity[i] > gravity[j]:
            cnt+=1
    if max_cnt < cnt:
        max_cnt=cnt

In [124]:
print(max_cnt)

7


In [134]:
import numpy as py

arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1]])
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [135]:
arr.T # 전치행렬 : 행과 열을 바꿈

array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])

In [137]:
np.dot(arr, arr.T)

array([[ 1,  2,  3,  0,  0],
       [ 2,  9,  8,  1, -1],
       [ 3,  8, 49, -8,  8],
       [ 0,  1, -8,  2, -2],
       [ 0, -1,  8, -2,  2]])

In [138]:
arr @ arr.T

array([[ 1,  2,  3,  0,  0],
       [ 2,  9,  8,  1, -1],
       [ 3,  8, 49, -8,  8],
       [ 0,  1, -8,  2, -2],
       [ 0, -1,  8, -2,  2]])

In [139]:
#3행2열 행렬, 2행4열 행렬 생성(난수:1~10)
#행렬 곱셈 출력

In [147]:
arr1 = np.random.randint(1, 11, size=(3,2))
arr2 = np.random.randint(1, 11, size=(2,4))

In [148]:
arr1

array([[9, 2],
       [8, 9],
       [5, 9]])

In [149]:
arr2

array([[ 4,  8,  4,  6],
       [ 7,  8,  9, 10]])

In [150]:
#앞 열과 뒤 행이 같을 때 곱셈 가능
np.dot(arr1, arr2)

array([[ 50,  88,  54,  74],
       [ 95, 136, 113, 138],
       [ 83, 112, 101, 120]])

In [151]:
arr1 @ arr2

array([[ 50,  88,  54,  74],
       [ 95, 136, 113, 138],
       [ 83, 112, 101, 120]])

In [152]:
samples=np.random.standard_normal(size=(4,4))
samples

array([[ 0.13180218, -0.03733993,  0.51681124, -2.10693897],
       [ 0.37792604, -0.20195612, -2.17235444,  1.68576989],
       [ 1.56470685,  0.50838606,  0.93646811,  0.02452905],
       [-0.89530252, -0.41502187, -0.48775946, -1.00239601]])

In [153]:
np.mean(samples) #np.mean 평균을 구하는 함수

-0.09829186790869437

In [154]:
np.std(samples)

1.0640689682265436

In [155]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
#[1.1, 2.2, 1.3, 1.4, 2.5]

In [163]:
[(x if c else y) for x, y, c in zip(xarr, yarr, cond)]

[1.1, 2.2, 1.3, 1.4, 2.5]

In [164]:
(xarr*cond) + (yarr*~cond)

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [165]:
#np.where(조건, 참 , 거짓)

In [168]:
np.where(cond, xarr, yarr)

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [169]:
arr=np.random.standard_normal((4,4))
arr

array([[-0.47182636,  0.09979276,  0.47518239, -0.03218729],
       [ 0.90335289,  0.16586562,  0.57503276,  0.07332474],
       [ 0.51664591, -0.15193631,  0.20530178, -1.05498658],
       [ 1.5835547 , -1.12920989,  0.00389426,  0.54240343]])

In [170]:
#음수 -> 0, 양수 -> 그대로

In [172]:
np.where(arr<0, 0, arr)

array([[0.        , 0.09979276, 0.47518239, 0.        ],
       [0.90335289, 0.16586562, 0.57503276, 0.07332474],
       [0.51664591, 0.        , 0.20530178, 0.        ],
       [1.5835547 , 0.        , 0.00389426, 0.54240343]])

In [175]:
import pandas as pd
import numpy as np

lst_A = {'제품':['milk','juice','bread','icecream'],
         '수량':[3,5,10,2],
         '제조일시':['2020-01-01 01:00:00','2019-12-20 15:01:00','2019-12-31 00:00:00','2020-01-02 02:03:01']}

df = pd.DataFrame(lst_A)
df
df['제조일시'] = pd.to_datetime(df['제조일시'])
df

제품  수량                제조일시
0      milk   3 2020-01-01 01:00:00
1     juice   5 2019-12-20 15:01:00
2     bread  10 2019-12-31 00:00:00
3  icecream   2 2020-01-02 02:03:01

In [176]:
#수량이 5 미만 -> 적정, 그렇지 않으면 -> 초과
#"초과여부" 열에 추가

In [182]:
df["초과여부"] = np.where(df["수량"]<5, "적정", "초과")

In [183]:
df

제품  수량                제조일시 초과여부
0      milk   3 2020-01-01 01:00:00   적정
1     juice   5 2019-12-20 15:01:00   초과
2     bread  10 2019-12-31 00:00:00   초과
3  icecream   2 2020-01-02 02:03:01   적정

In [184]:
#"제품종류" 열추가
#"제품" 열 값이 "juice" -> 음료, 아니면 -> "간식"

In [192]:
df["제품종류"]=np.where((df["제품"]=="juice") | (df["제품"]=="milk"), "음료", "간식")

In [193]:
df

제품  수량                제조일시 초과여부 제품종류
0      milk   3 2020-01-01 01:00:00   적정   음료
1     juice   5 2019-12-20 15:01:00   초과   음료
2     bread  10 2019-12-31 00:00:00   초과   간식
3  icecream   2 2020-01-02 02:03:01   적정   간식

In [194]:
arr

array([[-0.47182636,  0.09979276,  0.47518239, -0.03218729],
       [ 0.90335289,  0.16586562,  0.57503276,  0.07332474],
       [ 0.51664591, -0.15193631,  0.20530178, -1.05498658],
       [ 1.5835547 , -1.12920989,  0.00389426,  0.54240343]])

In [195]:
np.mean(arr)

0.14401280012694329

In [197]:
arr.mean()

0.14401280012694329

In [198]:
np.sum(arr)

2.3042048020310926

In [199]:
arr.sum()

2.3042048020310926

In [200]:
arr

array([[-0.47182636,  0.09979276,  0.47518239, -0.03218729],
       [ 0.90335289,  0.16586562,  0.57503276,  0.07332474],
       [ 0.51664591, -0.15193631,  0.20530178, -1.05498658],
       [ 1.5835547 , -1.12920989,  0.00389426,  0.54240343]])

In [204]:
arr=np.arange(10,15)
arr

array([10, 11, 12, 13, 14])

In [205]:
arr.cumsum() #누적합

array([10, 21, 33, 46, 60])

In [206]:
arr=np.arange(10,16).reshape(3,2)
arr

array([[10, 11],
       [12, 13],
       [14, 15]])

In [207]:
arr.cumsum(axis=0)

array([[10, 11],
       [22, 24],
       [36, 39]])

In [208]:
arr.cumsum(axis=1)

array([[10, 21],
       [12, 25],
       [14, 29]])

In [209]:
arr

array([[10, 11],
       [12, 13],
       [14, 15]])

In [215]:
arr.sum()
(arr>=13).sum()

3

In [216]:
arr[arr>=13] #불린참조 True 값만 출력

array([13, 14, 15])

In [217]:
arr[arr>=13].sum()

42

In [223]:
arr

array([[10, 11],
       [12, 13],
       [14, 15]])

In [224]:
brr = arr[[1, 0, 2]]

In [225]:
brr

array([[12, 13],
       [10, 11],
       [14, 15]])

In [227]:
brr.sort(axis = 0)
brr

array([[10, 11],
       [12, 13],
       [14, 15]])

In [228]:
brr.sort(axis = 1)
brr

array([[10, 11],
       [12, 13],
       [14, 15]])

In [229]:
names = np.array(["Bob", "Will", "Joe", "Bob", "Will", "Joe", "Joe"])

In [230]:
np.unique(names) #중복제거

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [231]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

array([1, 2, 3, 4])

In [232]:
set(names)

{'Bob', 'Joe', 'Will'}

In [235]:
np.random.rand(3)

array([0.88450345, 0.44230462, 0.09187577])

In [236]:
np.random.seed(20230907) #동일한 난수 출력

In [237]:
np.random.rand(3)

array([0.64824332, 0.27289441, 0.9663242 ])

In [238]:
x=np.arange(10)

In [239]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [254]:
np.random.seed(20230907)

In [255]:
np.random.shuffle(x) #데이터를 섞음

In [256]:
x

array([1, 5, 2, 8, 4, 3, 0, 9, 6, 7])

In [272]:
np.random.choice(x) # x-1

0

In [273]:
np.random.choice(5, 3) # 0~4까지 숫자 3개 랜덤추출

array([0, 1, 0])

In [276]:
np.random.choice(5, 3, replace=False) #중복되는 수가 나오지 않음

array([4, 3, 1])

In [277]:
np.random.choice(5, 10, replace=False) #0~4까지 10개 숫자 중복없이 생성 불가능

ValueError: Cannot take a larger sample than population when 'replace=False'

In [278]:
np.random.choice(5, 10, replace=True)

array([1, 3, 2, 0, 1, 3, 4, 1, 1, 2])

In [290]:
np.random.choice(45, 6, replace=False)+1

array([35, 33, 40,  6, 20, 12])