In [19]:
import numpy as np

In [9]:
ar = np.array([1,2,3])
ar

array([1, 2, 3])

In [8]:
ar = np.array([1.1,2,3]) #배열 안에는 같은 타입
ar

array([1.1, 2. , 3. ])

In [6]:
type(ar)

numpy.ndarray

In [10]:
myarr = np.arange(1000000)
mylist = list(np.arange(1000000))

In [14]:
list(np.arange(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [15]:
%timeit myarr2 = myarr*2
%timeit mylist2 = [x*2 for x in mylist] #list 보다 배열로 처리하는게 훨씬 빠름(numpy 사용 이유)

1.05 ms ± 6.76 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
64.6 ms ± 569 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [21]:
data = np.array([[1, -0.1, 2], [0, -3, 6]])
data

array([[ 1. , -0.1,  2. ],
       [ 0. , -3. ,  6. ]])

In [22]:
data*2 #파이썬 list에서는 안됨

array([[ 2. , -0.2,  4. ],
       [ 0. , -6. , 12. ]])

In [23]:
data + data #파이썬 list에서는 안됨

array([[ 2. , -0.2,  4. ],
       [ 0. , -6. , 12. ]])

In [24]:
list(data + data)

[array([ 2. , -0.2,  4. ]), array([ 0., -6., 12.])]

In [28]:
arr = np.array([1,2,3])
arr.ndim #차원
arr.dtype 

dtype('int32')

In [31]:
arr*3+1 #파이썬 list에서는 안됨

array([ 4,  7, 10])

In [32]:
arr == 2 #파이썬 list에서는 안됨

array([False,  True, False])

In [33]:
arr > 2 #파이썬 list에서는 안됨

array([False, False,  True])

In [34]:
(arr == 2) | (arr > 2)

array([False,  True,  True])

In [35]:
type(arr) #arr 자체의 타입

numpy.ndarray

In [36]:
arr.dtype #배열에 저장되어 있는 데이터의 type

dtype('int32')

In [41]:
np.zeros(10)
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [43]:
np.ones(10)
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [44]:
np.ones(10)*2

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [45]:
arr

array([1, 2, 3])

In [46]:
arr2 = np.ones(3)

In [47]:
arr2

array([1., 1., 1.])

In [48]:
arr+arr2

array([2., 3., 4.])

In [49]:
arr*arr2

array([1., 2., 3.])

In [50]:
arr1=arr.astype(np.float64) #type 변환

In [53]:
arr1=arr1.astype(np.int32)

In [54]:
arr1.dtype

dtype('int32')

In [55]:
arr.astype(float)

array([1., 2., 3.])

In [56]:
arr>arr2

array([False,  True,  True])

In [58]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
arr[5:8]

array([5, 6, 7])

In [60]:
arr[5:8] = 100
arr

array([  0,   1,   2,   3,   4, 100, 100, 100,   8,   9])

In [61]:
hund = arr[5:8]
hund

array([100, 100, 100])

In [62]:
arr=1

In [63]:
arr

1

In [64]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
arr[:]=10

In [66]:
arr

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [72]:
arr2d=np.arange(1,10).reshape(3,3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
arr2d[0]

array([1, 2, 3])

In [73]:
arr2d[1][0]

4

In [74]:
arr2d[1,0]

4

In [ ]:
#1~12 까지 값으로 3행 4열 생성, 10을 참조

In [80]:
arr=np.arange(1, 13).reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [81]:
arr[2][1]

10

In [83]:
len(arr) #3행

3

In [84]:
len(arr[0]) #4열

4

In [90]:
d=np.arange(1,25).reshape(2,3,4)
d
#3차원 배열 (깊이(차원), 행, 열)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [91]:
len(d)

2

In [92]:
len(d[0])

3

In [93]:
len(d[0][0])

4

In [94]:
d.ndim #3차원

3

In [95]:
d.shape

(2, 3, 4)

In [96]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [97]:
np.sum(arr)

78

In [98]:
np.sum(arr, axis=0) #같은 열끼리 덧셈, 차원 감소

array([15, 18, 21, 24])

In [99]:
np.sum(arr, axis=1) #같은 행끼리 덧셈, 차원 감소

array([10, 26, 42])

In [100]:
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [101]:
np.sum(d)

300

In [102]:
np.sum(d, axis=0) #차원(축)을 기준으로 합계, 차원 감소 (,3,4)

array([[14, 16, 18, 20],
       [22, 24, 26, 28],
       [30, 32, 34, 36]])

In [103]:
np.sum(d, axis=1) #행 기준으로 합계 (2,,4)

array([[15, 18, 21, 24],
       [51, 54, 57, 60]])

In [104]:
np.sum(d, axis=2) #열 기준으로 합계 (2, 3,)

array([[10, 26, 42],
       [58, 74, 90]])

In [105]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [108]:
arr[-1,-1] #[행,열]

12

In [109]:
arr[0,:]

array([1, 2, 3, 4])

In [111]:
arr[:,1]

array([ 2,  6, 10])

In [112]:
arr[:,2]

array([ 3,  7, 11])

In [114]:
arr[1,2:]

array([7, 8])

In [116]:
arr[2,:2]

array([ 9, 10])

In [117]:
a=np.array([1,2,3])
b=np.array([True,False,True])

In [ ]:
#불린참조 : True에 해당되는 자료를 참조

In [118]:
a

array([1, 2, 3])

In [ ]:
#b에 저장된 값이 True인 위치의 a배열 요소값을 참조

In [119]:
a[b]

array([1, 3])

In [ ]:
#arr배열에서 4의 배수만 추출

In [124]:
arr%4 #arr 배열의 요소를 4로 나눈 나머지

array([[1, 2, 3, 0],
       [1, 2, 3, 0],
       [1, 2, 3, 0]], dtype=int32)

In [125]:
arr%4 == 0 #불린 값

array([[False, False, False,  True],
       [False, False, False,  True],
       [False, False, False,  True]])

In [126]:
arr[arr%4 == 0]

array([ 4,  8, 12])

In [127]:
a=np.arange(11,20)

In [128]:
a

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [130]:
a[np.array([0,3,5])]

array([11, 14, 16])

In [131]:
a[np.array([0,3,5,5,5,5,5,5,5,5,5])]

array([11, 14, 16, 16, 16, 16, 16, 16, 16, 16, 16])

In [132]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [133]:
arr[:,:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [134]:
arr[:,[True, False, True, False]]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [135]:
arr[[2,0,1],:] #2 0 1 행의 순서로 참조

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [136]:
brr=arr

In [137]:
arr[1,0]=50

In [138]:
arr

array([[ 1,  2,  3,  4],
       [50,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [139]:
brr

array([[ 1,  2,  3,  4],
       [50,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [141]:
crr=arr.copy()
crr

array([[ 1,  2,  3,  4],
       [50,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [142]:
arr[2,0]=90

In [143]:
arr

array([[ 1,  2,  3,  4],
       [50,  6,  7,  8],
       [90, 10, 11, 12]])

In [144]:
crr

array([[ 1,  2,  3,  4],
       [50,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [145]:
brr

array([[ 1,  2,  3,  4],
       [50,  6,  7,  8],
       [90, 10, 11, 12]])

In [146]:
names=np.array(["Kim", "Park", "Lee"])
data=np.array([[4, 2], [0, 2], [-1,2]])

In [147]:
names=="Kim"

array([ True, False, False])

In [148]:
data[names=="Kim"]

array([[4, 2]])

In [149]:
data[names=="Kim",1]

array([2])

In [150]:
names != "Park"

array([ True, False,  True])

In [151]:
data[names != "Park"]

array([[ 4,  2],
       [-1,  2]])

In [153]:
data[names != "Park",0]

array([ 4, -1])

In [154]:
~(names=="Kim") # ~은 not의 의미

array([False,  True,  True])

In [155]:
data[~(names=="Kim")]

array([[ 0,  2],
       [-1,  2]])

In [157]:
(names=="Park") | (names=="Lee")

array([False,  True,  True])

In [159]:
data[(names=="Park") | (names=="Lee")]

array([[ 0,  2],
       [-1,  2]])

In [160]:
data[data<0]=0 #data 요소값 중 음수인 값 0

In [161]:
data

array([[4, 2],
       [0, 2],
       [0, 2]])

In [162]:
names

array(['Kim', 'Park', 'Lee'], dtype='<U4')

In [163]:
data[names=="Lee"]

array([[0, 2]])

In [164]:
data[names=="Lee"]=999

In [165]:
data

array([[  4,   2],
       [  0,   2],
       [999, 999]])

In [175]:
arr=np.zeros((8,4)) #8행 4열 배열 생성

In [176]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [179]:
for i in range(8):
    arr[i]=i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])