In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [28]:
left

key1 key2  lval
0  foo  one     1
1  foo  two     2
2  bar  one     3

In [29]:
right

key1 key2  rval
0  foo  one     4
1  foo  one     5
2  bar  one     6
3  bar  two     7

In [27]:
left = pd.DataFrame({"key1": ["foo", "foo", "bar"],
                     "key2": ["one", "two", "one"],
                     "lval": pd.Series([1, 2, 3], dtype='Int64')})
right = pd.DataFrame({"key1": ["foo", "foo", "bar", "bar"],
                      "key2": ["one", "one", "one", "two"],
                      "rval": pd.Series([4, 5, 6, 7], dtype='Int64')})
pd.merge(left, right, on=["key1", "key2"], how="outer")

key1 key2  lval  rval
0  foo  one     1     4
1  foo  one     1     5
2  foo  two     2  <NA>
3  bar  one     3     6
4  bar  two  <NA>     7

In [30]:
pd.merge(left, right)

key1 key2  lval  rval
0  foo  one     1     4
1  foo  one     1     5
2  bar  one     3     6

In [31]:
pd.merge(left, right, on='key1')

key1 key2_x  lval key2_y  rval
0  foo    one     1    one     4
1  foo    one     1    one     5
2  foo    two     2    one     4
3  foo    two     2    one     5
4  bar    one     3    one     6
5  bar    one     3    two     7

In [33]:
pd.merge(left, right, on='key1', suffixes=('_left','_right')) #자동으로 부여되는 x, y 대신에 직섭 설정

key1 key2_left  lval key2_right  rval
0  foo       one     1        one     4
1  foo       one     1        one     5
2  foo       two     2        one     4
3  foo       two     2        one     5
4  bar       one     3        one     6
5  bar       one     3        two     7

In [34]:
left1 = pd.DataFrame({"key": ["a", "b", "a", "a", "b", "c"],
                      "value": pd.Series(range(6), dtype="Int64")})
right1 = pd.DataFrame({"group_val": [3.5, 7]}, index=["a", "b"])

In [35]:
left1

key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [36]:
right1

group_val
a        3.5
b        7.0

In [39]:
pd.merge(left1, right1, left_on='key', right_index=True) #left1의 key열과 right1의 인덱스를 합치기, c라는 key는 right1에 없어서 출력x

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0

In [40]:
pd.merge(left1, right1, left_on='key', right_index=True, how='inner') #inner는 디폴트

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0

In [41]:
pd.merge(left1, right1, left_on='key', right_index=True, how='outer') #key의 c 값도 추가

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0
5   c      5        NaN

In [43]:
pd.merge(left1, right1, left_on='key', right_index=True, how='outer').reset_index(drop=True) #인덱스 번호 정렬

key  value  group_val
0   a      0        3.5
1   a      2        3.5
2   a      3        3.5
3   b      1        7.0
4   b      4        7.0
5   c      5        NaN

In [44]:
lefth = pd.DataFrame({"key1": ["Ohio", "Ohio", "Ohio",
                               "Nevada", "Nevada"],
                      "key2": [2000, 2001, 2002, 2001, 2002],
                      "data": pd.Series(range(5), dtype="Int64")})

In [45]:
lefth

key1  key2  data
0    Ohio  2000     0
1    Ohio  2001     1
2    Ohio  2002     2
3  Nevada  2001     3
4  Nevada  2002     4

In [46]:
righth_index = pd.MultiIndex.from_arrays(
    [
        ["Nevada", "Nevada", "Ohio", "Ohio", "Ohio", "Ohio"],
        [2001, 2000, 2000, 2000, 2001, 2002]
    ]
)

In [47]:
righth_index

MultiIndex([('Nevada', 2001),
            ('Nevada', 2000),
            (  'Ohio', 2000),
            (  'Ohio', 2000),
            (  'Ohio', 2001),
            (  'Ohio', 2002)],
           )

In [48]:
righth = pd.DataFrame({"event1": pd.Series([0, 2, 4, 6, 8, 10], dtype="Int64",
                                           index=righth_index),
                       "event2": pd.Series([1, 3, 5, 7, 9, 11], dtype="Int64",
                                           index=righth_index)})

In [49]:
righth

event1  event2
Nevada 2001       0       1
       2000       2       3
Ohio   2000       4       5
       2000       6       7
       2001       8       9
       2002      10      11

In [52]:
lefth

key1  key2  data
0    Ohio  2000     0
1    Ohio  2001     1
2    Ohio  2002     2
3  Nevada  2001     3
4  Nevada  2002     4

In [53]:
pd.merge(lefth, righth, left_on=['key1','key2'], right_index=True)

key1  key2  data  event1  event2
0    Ohio  2000     0       4       5
0    Ohio  2000     0       6       7
1    Ohio  2001     1       8       9
2    Ohio  2002     2      10      11
3  Nevada  2001     3       0       1

In [54]:
pd.merge(lefth, righth, left_on=['key1','key2'], right_index=True, how='outer')

key1  key2  data  event1  event2
0    Ohio  2000     0       4       5
0    Ohio  2000     0       6       7
1    Ohio  2001     1       8       9
2    Ohio  2002     2      10      11
3  Nevada  2001     3       0       1
4  Nevada  2002     4    <NA>    <NA>
4  Nevada  2000  <NA>       2       3

In [55]:
left2 = pd.DataFrame([[1., 2.], [3., 4.], [5., 6.]],
                     index=["a", "c", "e"],
                     columns=["Ohio", "Nevada"]).astype("Int64")
right2 = pd.DataFrame([[7., 8.], [9., 10.], [11., 12.], [13, 14]],
                      index=["b", "c", "d", "e"],
                      columns=["Missouri", "Alabama"]).astype("Int64")

In [56]:
left2

Ohio  Nevada
a     1       2
c     3       4
e     5       6

In [57]:
right2

Missouri  Alabama
b         7        8
c         9       10
d        11       12
e        13       14

In [62]:
pd.merge(left2, right2, left_index=True, right_index=True) #인덱스끼리 합치기

Ohio  Nevada  Missouri  Alabama
c     3       4         9       10
e     5       6        13       14

In [63]:
pd.merge(left2, right2, left_index=True, right_index=True, how='outer')

Ohio  Nevada  Missouri  Alabama
a     1       2      <NA>     <NA>
b  <NA>    <NA>         7        8
c     3       4         9       10
d  <NA>    <NA>        11       12
e     5       6        13       14

In [64]:
left2

Ohio  Nevada
a     1       2
c     3       4
e     5       6

In [65]:
right2

Missouri  Alabama
b         7        8
c         9       10
d        11       12
e        13       14

In [66]:
left2.join(right2) #join 함수 왼쪽에 있는게 주체(여기선 left2), 주체는 다 출력되고 주체와 공통된 것만 right2에서 출력

Ohio  Nevada  Missouri  Alabama
a     1       2      <NA>     <NA>
c     3       4         9       10
e     5       6        13       14

In [67]:
left2.join(right2, how='inner') #양쪽에 공통된 것들만 출력

Ohio  Nevada  Missouri  Alabama
c     3       4         9       10
e     5       6        13       14

In [68]:
left2.join(right2, how='outer') #전체가 다 출력

Ohio  Nevada  Missouri  Alabama
a     1       2      <NA>     <NA>
b  <NA>    <NA>         7        8
c     3       4         9       10
d  <NA>    <NA>        11       12
e     5       6        13       14

In [69]:
left1

key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [70]:
right1

group_val
a        3.5
b        7.0

In [71]:
left1.join(right1)

key  value  group_val
0   a      0        NaN
1   b      1        NaN
2   a      2        NaN
3   a      3        NaN
4   b      4        NaN
5   c      5        NaN

In [72]:
left1.join(right1, on='key') #left1의 key라는 열인덱스로 right1의 인덱스에 합치기

key  value  group_val
0   a      0        3.5
1   b      1        7.0
2   a      2        3.5
3   a      3        3.5
4   b      4        7.0
5   c      5        NaN

In [73]:
another = pd.DataFrame([[7., 8.], [9., 10.], [11., 12.], [16., 17.]], #데이터프레임 만들 때 이중리스면 같이 묶인 것끼리 같은 행
                       index=["a", "c", "e", "f"],
                       columns=["New York", "Oregon"])
another

New York  Oregon
a       7.0     8.0
c       9.0    10.0
e      11.0    12.0
f      16.0    17.0

In [74]:
left2

Ohio  Nevada
a     1       2
c     3       4
e     5       6

In [75]:
right2

Missouri  Alabama
b         7        8
c         9       10
d        11       12
e        13       14

In [76]:
left2.join(right2)

Ohio  Nevada  Missouri  Alabama
a     1       2      <NA>     <NA>
c     3       4         9       10
e     5       6        13       14

In [78]:
left2.join(right2).join(another)

Ohio  Nevada  Missouri  Alabama  New York  Oregon
a     1       2      <NA>     <NA>       7.0     8.0
c     3       4         9       10       9.0    10.0
e     5       6        13       14      11.0    12.0

In [80]:
left2.join([right2,another]) #여러개의 데이터프레임 결합할때 리스트 구조를 사용

Ohio  Nevada  Missouri  Alabama  New York  Oregon
a     1       2      <NA>     <NA>       7.0     8.0
c     3       4         9       10       9.0    10.0
e     5       6        13       14      11.0    12.0

In [77]:
left2.join(right2, how='outer')

Ohio  Nevada  Missouri  Alabama
a     1       2      <NA>     <NA>
b  <NA>    <NA>         7        8
c     3       4         9       10
d  <NA>    <NA>        11       12
e     5       6        13       14

In [79]:
left2.join(right2, how='outer').join(another)

Ohio  Nevada  Missouri  Alabama  New York  Oregon
a     1       2      <NA>     <NA>       7.0     8.0
b  <NA>    <NA>         7        8       NaN     NaN
c     3       4         9       10       9.0    10.0
d  <NA>    <NA>        11       12       NaN     NaN
e     5       6        13       14      11.0    12.0

In [81]:
left2.join([right2,another], how='outer') #여러개의 데이터프레임 결합할때 리스트 구조를 사용

Ohio  Nevada  Missouri  Alabama  New York  Oregon
a     1       2      <NA>     <NA>       7.0     8.0
c     3       4         9       10       9.0    10.0
e     5       6        13       14      11.0    12.0
b  <NA>    <NA>         7        8       NaN     NaN
d  <NA>    <NA>        11       12       NaN     NaN
f  <NA>    <NA>      <NA>     <NA>      16.0    17.0

In [82]:
#배열에 대한 연결
arr = np.arange(12).reshape((3, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.concatenate
pd.concat #두개 다 연결해주는 함수임

In [83]:
np.concatenate([arr,arr]) #위아래로 연결

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [84]:
np.concatenate([arr,arr], axis=0) #axis=0이 디폴트

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [85]:
np.concatenate([arr,arr], axis=1) #좌우로 연결

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [86]:
arr2 = np.arange(20).reshape((4, 5))
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [87]:
np.concatenate([arr,arr2]) #열의 개수 맞지 않아서 에러

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 5

In [88]:
np.concatenate([arr,arr2], axis=1) #행의 개수가 맞이 않아서 에러

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 4

In [89]:
arr3 = np.arange(15).reshape((3, 5))
arr3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [90]:
np.concatenate([arr,arr3]) #열의 개수가 맞지 않아서 에러

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 5

In [91]:
np.concatenate([arr,arr3], axis=1) #행의 개수가 같으므롤 좌우로 연결

array([[ 0,  1,  2,  3,  0,  1,  2,  3,  4],
       [ 4,  5,  6,  7,  5,  6,  7,  8,  9],
       [ 8,  9, 10, 11, 10, 11, 12, 13, 14]])

In [92]:
#시리즈나 데이터프레임에 대한 연결
s1 = pd.Series([0, 1], index=["a", "b"], dtype="Int64")
s2 = pd.Series([2, 3, 4], index=["c", "d", "e"], dtype="Int64")
s3 = pd.Series([5, 6], index=["f", "g"], dtype="Int64")

In [93]:
s1

a    0
b    1
dtype: Int64

In [94]:
s2

c    2
d    3
e    4
dtype: Int64

In [95]:
s3

f    5
g    6
dtype: Int64

In [97]:
pd.concat([s1,s2,s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: Int64

In [98]:
pd.concat([s1,s2,s3], axis=0) #axis=0이 디폴트

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: Int64

In [99]:
pd.concat([s1,s2,s3], axis=1) #좌우(행 인덱스)

0     1     2
a     0  <NA>  <NA>
b     1  <NA>  <NA>
c  <NA>     2  <NA>
d  <NA>     3  <NA>
e  <NA>     4  <NA>
f  <NA>  <NA>     5
g  <NA>  <NA>     6

In [100]:
s1

a    0
b    1
dtype: Int64

In [101]:
s3

f    5
g    6
dtype: Int64

In [102]:
pd.concat([s1,s3])

a    0
b    1
f    5
g    6
dtype: Int64

In [103]:
s4=pd.concat([s1,s3])
s4

a    0
b    1
f    5
g    6
dtype: Int64

In [104]:
pd.concat([s1,s4])

a    0
b    1
a    0
b    1
f    5
g    6
dtype: Int64

In [105]:
pd.concat([s1,s4], axis=1)

0  1
a     0  0
b     1  1
f  <NA>  5
g  <NA>  6

In [106]:
pd.concat([s1,s4], axis=1, join='inner') #행인덱스가 같은 것끼리만 출력

0  1
a  0  0
b  1  1

In [107]:
pd.concat([s1,s4], axis=1, join='outer') #디폴트

0  1
a     0  0
b     1  1
f  <NA>  5
g  <NA>  6

In [108]:
s1

a    0
b    1
dtype: Int64

In [109]:
s2

c    2
d    3
e    4
dtype: Int64

In [110]:
s3

f    5
g    6
dtype: Int64

In [111]:
pd.concat([s1,s2,s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: Int64

In [112]:
pd.concat([s1,s2,s3], keys=['one','two','three']) #행인덱스의 이름 지정

one    a    0
       b    1
two    c    2
       d    3
       e    4
three  f    5
       g    6
dtype: Int64

In [113]:
type(pd.concat([s1,s2,s3], keys=['one','two','three'])) #멀티인덱스 시리즈

pandas.core.series.Series

In [114]:
res=pd.concat([s1,s2,s3], keys=['one','two','three'])
res.unstack() #상위 인덱스가 행인덱스 하위 인덱스가 열인덱스

a     b     c     d     e     f     g
one       0     1  <NA>  <NA>  <NA>  <NA>  <NA>
two    <NA>  <NA>     2     3     4  <NA>  <NA>
three  <NA>  <NA>  <NA>  <NA>  <NA>     5     6

In [117]:
pd.concat([s1,s2,s3],axis=1, keys=['one','two','three'])

one   two  three
a     0  <NA>   <NA>
b     1  <NA>   <NA>
c  <NA>     2   <NA>
d  <NA>     3   <NA>
e  <NA>     4   <NA>
f  <NA>  <NA>      5
g  <NA>  <NA>      6

In [118]:
#데이터프레임에 관한 concat
df1 = pd.DataFrame(np.arange(6).reshape(3, 2), index=["a", "b", "c"],
                   columns=["one", "two"])
df2 = pd.DataFrame(5 + np.arange(4).reshape(2, 2), index=["a", "c"],
                   columns=["three", "four"])

In [125]:
df3 = pd.DataFrame(10 + np.arange(4).reshape(2, 2), index=["a", "c"],
                   columns=["one", "five"])

In [126]:
df3

one  five
a   10    11
c   12    13

In [120]:
df1

one  two
a    0    1
b    2    3
c    4    5

In [121]:
df2

three  four
a      5     6
c      7     8

In [122]:
pd.concat([df1,df2]) #위아래, 같은 열인덱스끼리 연결, 지금의 경우 같은 이름의 열인덱스가 없음

one  two  three  four
a  0.0  1.0    NaN   NaN
b  2.0  3.0    NaN   NaN
c  4.0  5.0    NaN   NaN
a  NaN  NaN    5.0   6.0
c  NaN  NaN    7.0   8.0

In [123]:
pd.concat([df1,df2], axis=0) #디폴트

one  two  three  four
a  0.0  1.0    NaN   NaN
b  2.0  3.0    NaN   NaN
c  4.0  5.0    NaN   NaN
a  NaN  NaN    5.0   6.0
c  NaN  NaN    7.0   8.0

In [124]:
pd.concat([df1,df2], axis=1) #공통 행인덱스끼리 좌우로 연결

one  two  three  four
a    0    1    5.0   6.0
b    2    3    NaN   NaN
c    4    5    7.0   8.0

In [127]:
pd.concat([df1,df3]) #공통된 이름의 one 열인덱스가 존재하므로 위아래 연결

one  two  five
a    0  1.0   NaN
b    2  3.0   NaN
c    4  5.0   NaN
a   10  NaN  11.0
c   12  NaN  13.0

In [128]:
pd.concat([df1,df2], axis=1, keys=['level1','level2']) #상위 열인덱스 이름 추가

level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [129]:
df1 = pd.DataFrame(np.random.standard_normal((3, 4)),
                   columns=["a", "b", "c", "d"])
df2 = pd.DataFrame(np.random.standard_normal((2, 3)),
                   columns=["b", "d", "a"])

In [130]:
df1

a         b         c         d
0 -0.163752 -1.127313  0.008315  0.595692
1 -0.015313 -2.396367  0.429844  0.283778
2 -0.689021 -0.638632 -0.488335 -0.622895

In [131]:
df2

b         d         a
0  0.420492 -0.613627  0.873371
1 -0.324662  0.259378 -0.181704

In [132]:
pd.concat([df1,df2])

a         b         c         d
0 -0.163752 -1.127313  0.008315  0.595692
1 -0.015313 -2.396367  0.429844  0.283778
2 -0.689021 -0.638632 -0.488335 -0.622895
0  0.873371  0.420492       NaN -0.613627
1 -0.181704 -0.324662       NaN  0.259378

In [133]:
pd.concat([df1,df2]).reset_index()

index         a         b         c         d
0      0 -0.163752 -1.127313  0.008315  0.595692
1      1 -0.015313 -2.396367  0.429844  0.283778
2      2 -0.689021 -0.638632 -0.488335 -0.622895
3      0  0.873371  0.420492       NaN -0.613627
4      1 -0.181704 -0.324662       NaN  0.259378

In [134]:
pd.concat([df1,df2]).reset_index(drop=True)

a         b         c         d
0 -0.163752 -1.127313  0.008315  0.595692
1 -0.015313 -2.396367  0.429844  0.283778
2 -0.689021 -0.638632 -0.488335 -0.622895
3  0.873371  0.420492       NaN -0.613627
4 -0.181704 -0.324662       NaN  0.259378

In [135]:
pd.concat([df1,df2], ignore_index=True)

a         b         c         d
0 -0.163752 -1.127313  0.008315  0.595692
1 -0.015313 -2.396367  0.429844  0.283778
2 -0.689021 -0.638632 -0.488335 -0.622895
3  0.873371  0.420492       NaN -0.613627
4 -0.181704 -0.324662       NaN  0.259378

In [136]:
a = pd.Series([np.nan, 2.5, 0.0, 3.5, 4.5, np.nan],
              index=["f", "e", "d", "c", "b", "a"])
b = pd.Series([0., np.nan, 2., np.nan, np.nan, 5.],
              index=["a", "b", "c", "d", "e", "f"])

In [137]:
a

f    NaN
e    2.5
d    0.0
c    3.5
b    4.5
a    NaN
dtype: float64

In [138]:
b

a    0.0
b    NaN
c    2.0
d    NaN
e    NaN
f    5.0
dtype: float64

In [ ]:
#a의 데이터가 결측값인 경우 b의 데이터를 추출, 결측값이 아니라면 a의 데이터 그대로 사용
#np.where(조건, 참, 거짓)

In [139]:
pd.isna(a)

f     True
e    False
d    False
c    False
b    False
a     True
dtype: bool

In [140]:
np.where(pd.isna(a),b,a)

array([0. , 2.5, 0. , 3.5, 4.5, 5. ])

In [141]:
a.combine_first(b) #같은 기능의 함수

a    0.0
b    4.5
c    3.5
d    0.0
e    2.5
f    5.0
dtype: float64

In [142]:
df1 = pd.DataFrame({"a": [1., np.nan, 5., np.nan],
                    "b": [np.nan, 2., np.nan, 6.],
                    "c": range(2, 18, 4)})
df2 = pd.DataFrame({"a": [5., 4., np.nan, 3., 7.],
                    "b": [np.nan, 3., 4., 6., 8.]})

In [143]:
df1

a    b   c
0  1.0  NaN   2
1  NaN  2.0   6
2  5.0  NaN  10
3  NaN  6.0  14

In [144]:
df2

a    b
0  5.0  NaN
1  4.0  3.0
2  NaN  4.0
3  3.0  6.0
4  7.0  8.0

In [145]:
#df1의 결측값을 df2로 대체하여 합치기
df1.combine_first(df2)

a    b     c
0  1.0  NaN   2.0
1  4.0  2.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN

In [146]:
data = pd.DataFrame(np.arange(6).reshape((2, 3)),
                    index=pd.Index(["Ohio", "Colorado"], name="state"),
                    columns=pd.Index(["one", "two", "three"],
                    name="number"))
data

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [147]:
data.stack() #dataframe -> series

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int32

In [148]:
data.stack().unstack()

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [149]:
res=data.stack()
res

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int32

In [150]:
res.unstack()

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [151]:
res.unstack(level=0) #level=0에 해당되는 부분이 열인덱스로 지정

state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5

In [152]:
res.unstack(level=1)

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [153]:
res.unstack(level='state')

state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5

In [154]:
res.unstack(level='number')

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [155]:
s1 = pd.Series([0, 1, 2, 3], index=["a", "b", "c", "d"], dtype="Int64")
s2 = pd.Series([4, 5, 6], index=["c", "d", "e"], dtype="Int64")
data2 = pd.concat([s1, s2], keys=["one", "two"])
data2

one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: Int64

In [156]:
s1

a    0
b    1
c    2
d    3
dtype: Int64

In [157]:
s2

c    4
d    5
e    6
dtype: Int64

In [158]:
data2.unstack()

a     b  c  d     e
one     0     1  2  3  <NA>
two  <NA>  <NA>  4  5     6

In [159]:
data2.unstack().stack()

one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: Int64

In [160]:
data2.unstack().stack(dropna=False) #na값까지 출력

one  a       0
     b       1
     c       2
     d       3
     e    <NA>
two  a    <NA>
     b    <NA>
     c       4
     d       5
     e       6
dtype: Int64

In [162]:
res

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int32

In [282]:
df = pd.DataFrame({"left": res, "right": res + 5},
                  columns=pd.Index(["left", "right"], name="side"))
df

side             left  right
state    number             
Ohio     one        0      5
         two        1      6
         three      2      7
Colorado one        3      8
         two        4      9
         three      5     10

In [163]:
data

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [165]:
data=data.reindex(columns=['two','three','one']) #열 인덱스 순서 바꾸기
data

number    two  three  one
state                    
Ohio        1      2    0
Colorado    4      5    3

In [176]:
data = {
    "도시": ["서울", "서울", "서울", "부산", "부산", "부산", "인천", "인천"],
    "연도": ["2015", "2010", "2005", "2015", "2010", "2005", "2015", "2010"],
    "인구": [9904312, 9631482, 9762546, 3448737, 3393191, 3512547, 2890451, 263203],
    "지역": ["수도권", "수도권", "수도권", "경상권", "경상권", "경상권", "수도권", "수도권"]
}
cols = ["도시", "연도", "인구", "권역"]

In [167]:
data

{'도시': ['서울', '서울', '서울', '부산', '부산', '부산', '인천', '인천'],
 '연도': ['2015', '2010', '2005', '2015', '2010', '2005', '2015', '2010'],
 '인구': [9904312, 9631482, 9762546, 3448737, 3393191, 3512547, 2890451, 263203],
 '지역': ['수도권', '수도권', '수도권', '경상권', '경상권', '경상권', '수도권', '수도권']}

In [168]:
columns

['도시', '연도', '인구', '지역']

In [174]:
pd.DataFrame(data)

도시    연도       인구   지역
0  서울  2015  9904312  수도권
1  서울  2010  9631482  수도권
2  서울  2005  9762546  수도권
3  부산  2015  3448737  경상권
4  부산  2010  3393191  경상권
5  부산  2005  3512547  경상권
6  인천  2015  2890451  수도권
7  인천  2010   263203  수도권

In [ ]:
#열인덱스가 4개 feature 4개 4차원 데이터, 

In [177]:
pd.DataFrame(data, columns=cols)

도시    연도       인구   권역
0  서울  2015  9904312  NaN
1  서울  2010  9631482  NaN
2  서울  2005  9762546  NaN
3  부산  2015  3448737  NaN
4  부산  2010  3393191  NaN
5  부산  2005  3512547  NaN
6  인천  2015  2890451  NaN
7  인천  2010   263203  NaN

In [15]:
data = {
    "도시": ["서울", "서울", "서울", "부산", "부산", "부산", "인천", "인천"],
    "연도": ["2015", "2010", "2005", "2015", "2010", "2005", "2015", "2010"],
    "인구": [9904312, 9631482, 9762546, 3448737, 3393191, 3512547, 2890451, 263203],
    "지역": ["수도권", "수도권", "수도권", "경상권", "경상권", "경상권", "수도권", "수도권"]
}
columns = ["도시", "연도", "인구", "지역"]
df1 = pd.DataFrame(data, columns=columns)
df1

도시    연도       인구   지역
0  서울  2015  9904312  수도권
1  서울  2010  9631482  수도권
2  서울  2005  9762546  수도권
3  부산  2015  3448737  경상권
4  부산  2010  3393191  경상권
5  부산  2005  3512547  경상권
6  인천  2015  2890451  수도권
7  인천  2010   263203  수도권

In [179]:
df1.pivot('도시','연도','인구')
#pivot(행, 열, 데이터)

C:\Users\user\AppData\Local\Temp\ipykernel_5084\69723028.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.pivot will be keyword-only.
  df1.pivot('도시','연도','인구')


연도       2005       2010       2015
도시                                 
부산  3512547.0  3393191.0  3448737.0
서울  9762546.0  9631482.0  9904312.0
인천        NaN   263203.0  2890451.0

In [ ]:
#pivot과 pivot table 함수 사용 목적은 데이터의 구조를 변경하기 위함

In [181]:
df1.set_index('도시') #특정열의 인덱스를 행 인덱스로 설정

연도       인구   지역
도시                    
서울  2015  9904312  수도권
서울  2010  9631482  수도권
서울  2005  9762546  수도권
부산  2015  3448737  경상권
부산  2010  3393191  경상권
부산  2005  3512547  경상권
인천  2015  2890451  수도권
인천  2010   263203  수도권

In [184]:
df1.set_index(['도시','연도']).stack()

도시  연도      
서울  2015  인구    9904312
          지역        수도권
    2010  인구    9631482
          지역        수도권
    2005  인구    9762546
          지역        수도권
부산  2015  인구    3448737
          지역        경상권
    2010  인구    3393191
          지역        경상권
    2005  인구    3512547
          지역        경상권
인천  2015  인구    2890451
          지역        수도권
    2010  인구     263203
          지역        수도권
dtype: object

In [185]:
df1.set_index(['도시','연도'])['인구'] #대괄호 1개 시리즈로 출력

도시  연도  
서울  2015    9904312
    2010    9631482
    2005    9762546
부산  2015    3448737
    2010    3393191
    2005    3512547
인천  2015    2890451
    2010     263203
Name: 인구, dtype: int64

In [186]:
df1.set_index(['도시','연도'])[['인구']] #대괄호 2개 데이터프레임으로 출력

인구
도시 연도           
서울 2015  9904312
   2010  9631482
   2005  9762546
부산 2015  3448737
   2010  3393191
   2005  3512547
인천 2015  2890451
   2010   263203

In [188]:
df1.pivot('도시','연도','인구')

C:\Users\user\AppData\Local\Temp\ipykernel_5084\69723028.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.pivot will be keyword-only.
  df1.pivot('도시','연도','인구')


연도       2005       2010       2015
도시                                 
부산  3512547.0  3393191.0  3448737.0
서울  9762546.0  9631482.0  9904312.0
인천        NaN   263203.0  2890451.0

In [187]:
df1.set_index(['도시','연도'])[['인구']].unstack() #df1.pivot('도시','연도','인구')과 결과값 같음

인구                      
연도       2005       2010       2015
도시                                 
부산  3512547.0  3393191.0  3448737.0
서울  9762546.0  9631482.0  9904312.0
인천        NaN   263203.0  2890451.0

In [190]:
df1.pivot(['지역','도시'],'연도','인구')

C:\Users\user\AppData\Local\Temp\ipykernel_5084\2443284221.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.pivot will be keyword-only.
  df1.pivot(['지역','도시'],'연도','인구')


연도           2005       2010       2015
지역  도시                                 
경상권 부산  3512547.0  3393191.0  3448737.0
수도권 서울  9762546.0  9631482.0  9904312.0
    인천        NaN   263203.0  2890451.0

In [191]:
df1.pivot('지역','연도','인구') #수도권이면서 2015년에 해당하는 자료가 2 건 있으므로 에러 발생
#자료가 1건만 존재

C:\Users\user\AppData\Local\Temp\ipykernel_5084\2196381943.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.pivot will be keyword-only.
  df1.pivot('지역','연도','인구')


ValueError: Index contains duplicate entries, cannot reshape

In [ ]:
#pivot_table=pivot + groupby

In [4]:
np.random.seed(0)
df2 = pd.DataFrame({
    'key1': ['A', 'A', 'B', 'B', 'A'],
    'key2': ['one', 'two', 'one', 'two', 'one'],
    'data1': [1, 2, 3, 4, 5],
    'data2': [10, 20, 30, 40, 50]
})
df2

key1 key2  data1  data2
0    A  one      1     10
1    A  two      2     20
2    B  one      3     30
3    B  two      4     40
4    A  one      5     50

In [6]:
groups=df2.groupby('key1') #df2.groupby(df2.key2)랑 동일
groups

In [196]:
groups.groups

{'A': [0, 1, 4], 'B': [2, 3]}

In [197]:
groups.get_group('A')

key1 key2  data1  data2
0    A  one      1     10
1    A  two      2     20
4    A  one      5     50

In [198]:
groups.sum()

C:\Users\user\AppData\Local\Temp\ipykernel_5084\1171057664.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  groups.sum()


data1  data2
key1              
A         8     80
B         7     70

In [8]:
df2

key1 key2  data1  data2
0    A  one      1     10
1    A  two      2     20
2    B  one      3     30
3    B  two      4     40
4    A  one      5     50

In [ ]:
#df2의 data1열에 대해서만 그룹화, 그룹화 기준은 key1열

In [200]:
df2.data1

0    1
1    2
2    3
3    4
4    5
Name: data1, dtype: int64

In [201]:
df2.data1.groupby(df2.key1).sum()

key1
A    8
B    7
Name: data1, dtype: int64

In [203]:
df2.groupby('key1').sum()['data1']

C:\Users\user\AppData\Local\Temp\ipykernel_5084\860493886.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df2.groupby('key1').sum()['data1']


key1
A    8
B    7
Name: data1, dtype: int64

In [205]:
df2.groupby('key1')['data1'].sum() #효율적

key1
A    8
B    7
Name: data1, dtype: int64

In [11]:
df2.groupby('key1')['data1']

In [231]:
df2

key1 key2  data1  data2
0    A  one      1     10
1    A  two      2     20
2    B  one      3     30
3    B  two      4     40
4    A  one      5     50

In [210]:
df2.data1.groupby(df2.key1).sum()

key1
A    8
B    7
Name: data1, dtype: int64

In [211]:
df2.data1.groupby([df2.key1, df2.key2]).sum()

key1  key2
A     one     6
      two     2
B     one     3
      two     4
Name: data1, dtype: int64

In [220]:
df2.data1.groupby([df2.key1,df2.key2]).sum()

key1  key2
A     one     6
      two     2
B     one     3
      two     4
Name: data1, dtype: int64

In [234]:
df2.groupby([df2.key1,df2.key2]).data1.sum().unstack()

key2  one  two
key1          
A       6    2
B       3    4

In [221]:
df2.data1.groupby([df2.key1,df2.key2]).sum().unstack()

key2  one  two
key1          
A       6    2
B       3    4

In [13]:
df1

NameError: name 'df1' is not defined

In [227]:
df1.인구.groupby([df1.지역, df1.연도]).sum().unstack()

연도      2005     2010      2015
지역                             
경상권  3512547  3393191   3448737
수도권  9762546  9894685  12794763

In [17]:
df1.groupby([df1.지역,df1.연도])['인구'].sum().unstack()

연도      2005     2010      2015
지역                             
경상권  3512547  3393191   3448737
수도권  9762546  9894685  12794763

In [20]:
df1 = pd.DataFrame({
    '고객번호': [1001, 1002, 1003, 1004, 1005, 1006, 1007],
    '이름': ['둘리', '도우너', '또치', '길동', '희동', '마이콜', '영희']
}, columns=['고객번호', '이름'])
df1

고객번호   이름
0  1001   둘리
1  1002  도우너
2  1003   또치
3  1004   길동
4  1005   희동
5  1006  마이콜
6  1007   영희

In [21]:
df2 = pd.DataFrame({
    '고객번호': [1001, 1001, 1005, 1006, 1008, 1001],
    '금액': [10000, 20000, 15000, 5000, 100000, 30000]
}, columns=['고객번호', '금액'])
df2

고객번호      금액
0  1001   10000
1  1001   20000
2  1005   15000
3  1006    5000
4  1008  100000
5  1001   30000

In [22]:
pd.merge(df1,df2)

고객번호   이름     금액
0  1001   둘리  10000
1  1001   둘리  20000
2  1001   둘리  30000
3  1005   희동  15000
4  1006  마이콜   5000

In [237]:
#데이터프레임 합칠 떄 사용하는 함수 merge join concat
pd.merge(df1,df2) #동일한 열인덱스 있을 때

고객번호   이름     금액
0  1001   둘리  10000
1  1001   둘리  20000
2  1001   둘리  30000
3  1005   희동  15000
4  1006  마이콜   5000

In [238]:
pd.merge(df1,df2,how='outer') 

고객번호   이름        금액
0  1001   둘리   10000.0
1  1001   둘리   20000.0
2  1001   둘리   30000.0
3  1002  도우너       NaN
4  1003   또치       NaN
5  1004   길동       NaN
6  1005   희동   15000.0
7  1006  마이콜    5000.0
8  1007   영희       NaN
9  1008  NaN  100000.0

In [239]:
pd.merge(df1,df2,how='right') #df2를 기준으로 df1과 합치기

고객번호   이름      금액
0  1001   둘리   10000
1  1001   둘리   20000
2  1005   희동   15000
3  1006  마이콜    5000
4  1008  NaN  100000
5  1001   둘리   30000

In [24]:
df1 = pd.DataFrame({
    '품종': ['setosa', 'setosa', 'virginica', 'virginica'],
    '꽃잎길이': [1.4, 1.3, 1.5, 1.3]},
    columns=['품종', '꽃잎길이'])
df1

품종  꽃잎길이
0     setosa   1.4
1     setosa   1.3
2  virginica   1.5
3  virginica   1.3

In [25]:
df2 = pd.DataFrame({
    '품종': ['setosa', 'virginica', 'virginica', 'versicolor'],
    '꽃잎너비': [0.4, 0.3, 0.5, 0.3]},
    columns=['품종', '꽃잎너비'])
df2

품종  꽃잎너비
0      setosa   0.4
1   virginica   0.3
2   virginica   0.5
3  versicolor   0.3

In [245]:
pd.merge(df1,df2)

품종  꽃잎길이  꽃잎너비
0     setosa   1.4   0.4
1     setosa   1.3   0.4
2  virginica   1.5   0.3
3  virginica   1.5   0.5
4  virginica   1.3   0.3
5  virginica   1.3   0.5

In [26]:
df1 = pd.DataFrame({
    '고객명': ['춘향', '춘향', '몽룡'],
    '날짜': ['2018-01-01', '2018-01-02', '2018-01-01'],
    '데이터': ['20000', '30000', '100000']})
df1

고객명          날짜     데이터
0  춘향  2018-01-01   20000
1  춘향  2018-01-02   30000
2  몽룡  2018-01-01  100000

In [27]:
df2 = pd.DataFrame({
    '고객명': ['춘향', '몽룡'],
    '데이터': ['여자', '남자']})
df2

고객명 데이터
0  춘향  여자
1  몽룡  남자

In [28]:
pd.merge(df1,df2) #df1과 df2의 데이터 값이 서로 맞지 않아 아무것도 출력되지 않음

Empty DataFrame
Columns: [고객명, 날짜, 데이터]
Index: []

In [260]:
pd.merge(df1,df2,on='고객명') #고객명에 대한 열로만 합치기

고객명          날짜   데이터_x 데이터_y
0  춘향  2018-01-01   20000    여자
1  춘향  2018-01-02   30000    여자
2  몽룡  2018-01-01  100000    남자

In [254]:
df1 = pd.DataFrame({
    '고객명': ['춘향', '춘향', '몽룡'],
    '날짜': ['2018-01-01', '2018-01-02', '2018-01-01'],
    '데이터': ['20000', '30000', '100000']})
df1

고객명          날짜     데이터
0  춘향  2018-01-01   20000
1  춘향  2018-01-02   30000
2  몽룡  2018-01-01  100000

In [255]:
df2 = pd.DataFrame({
    '고객명': ['춘향', '몽룡'],
    '성별': ['여자', '남자']})
df2

고객명  성별
0  춘향  여자
1  몽룡  남자

In [256]:
pd.merge(df1,df2)

고객명          날짜     데이터  성별
0  춘향  2018-01-01   20000  여자
1  춘향  2018-01-02   30000  여자
2  몽룡  2018-01-01  100000  남자

In [261]:
df1 = pd.DataFrame({
    '품종': ['setosa', 'setosa', 'virginica', 'virginica'],
    '꽃잎길이': [1.4, 1.3, 1.5, 1.3]},
    columns=['품종', '꽃잎길이'])
df1

품종  꽃잎길이
0     setosa   1.4
1     setosa   1.3
2  virginica   1.5
3  virginica   1.3

In [262]:
df2 = pd.DataFrame({
    '품종': ['setosa', 'virginica', 'virginica', 'versicolor'],
    '꽃잎너비': [0.4, 0.3, 0.5, 0.3]},
    columns=['품종', '꽃잎너비'])
df2

품종  꽃잎너비
0      setosa   0.4
1   virginica   0.3
2   virginica   0.5
3  versicolor   0.3

In [263]:
pd.merge(df1,df2)

품종  꽃잎길이  꽃잎너비
0     setosa   1.4   0.4
1     setosa   1.3   0.4
2  virginica   1.5   0.3
3  virginica   1.5   0.5
4  virginica   1.3   0.3
5  virginica   1.3   0.5

In [265]:
df1 = pd.DataFrame({
    '이름': ['영희', '철수', '철수'],
    '성적': [1, 2, 3]})
df1

이름  성적
0  영희   1
1  철수   2
2  철수   3

In [267]:
df2 = pd.DataFrame({
    '성명': ['영희', '영희', '철수'],
    '성적2': [4, 5, 6]})
df2

성명  성적2
0  영희    4
1  영희    5
2  철수    6

In [268]:
pd.merge(df1,df2, left_on='이름', right_on='성명')

이름  성적  성명  성적2
0  영희   1  영희    4
1  영희   1  영희    5
2  철수   2  철수    6
3  철수   3  철수    6

In [269]:
df1 = pd.DataFrame({
    '도시': ['서울', '서울', '서울', '부산', '부산'],
    '연도': [2000, 2005, 2010, 2000, 2005],
    '인구': [9853972, 9762546, 9631482, 3655437, 3512547]})
df1

도시    연도       인구
0  서울  2000  9853972
1  서울  2005  9762546
2  서울  2010  9631482
3  부산  2000  3655437
4  부산  2005  3512547

In [270]:
df2 = pd.DataFrame(
    np.arange(12).reshape((6, 2)),
    index=[['부산', '부산', '서울', '서울', '서울', '서울'],
           [2000, 2005, 2000, 2005, 2010, 2015]],
    columns=['데이터1', '데이터2'])
df2

데이터1  데이터2
부산 2000     0     1
   2005     2     3
서울 2000     4     5
   2005     6     7
   2010     8     9
   2015    10    11

In [271]:
pd.merge(df1,df2, left_on=['도시','연도'], right_index=True)

도시    연도       인구  데이터1  데이터2
0  서울  2000  9853972     4     5
1  서울  2005  9762546     6     7
2  서울  2010  9631482     8     9
3  부산  2000  3655437     0     1
4  부산  2005  3512547     2     3

In [272]:
df1 = pd.DataFrame(
    [[1., 2.], [3., 4.], [5., 6.]],
    index=['a', 'c', 'e'],
    columns=['서울', '부산'])
df1

서울   부산
a  1.0  2.0
c  3.0  4.0
e  5.0  6.0

In [273]:
df2 = pd.DataFrame(
    [[7., 8.], [9., 10.], [11., 12.], [13, 14]],
    index=['b', 'c', 'd', 'e'],
    columns=['대구', '광주'])
df2

대구    광주
b   7.0   8.0
c   9.0  10.0
d  11.0  12.0
e  13.0  14.0

In [275]:
df1.join(df2, how='outer')

서울   부산    대구    광주
a  1.0  2.0   NaN   NaN
b  NaN  NaN   7.0   8.0
c  3.0  4.0   9.0  10.0
d  NaN  NaN  11.0  12.0
e  5.0  6.0  13.0  14.0

In [278]:
pd.concat([df1,df2])

서울   부산    대구    광주
a  1.0  2.0   NaN   NaN
c  3.0  4.0   NaN   NaN
e  5.0  6.0   NaN   NaN
b  NaN  NaN   7.0   8.0
c  NaN  NaN   9.0  10.0
d  NaN  NaN  11.0  12.0
e  NaN  NaN  13.0  14.0

In [281]:
pd.concat([df1,df2], axis=1, sort=True)

서울   부산    대구    광주
a  1.0  2.0   NaN   NaN
b  NaN  NaN   7.0   8.0
c  3.0  4.0   9.0  10.0
d  NaN  NaN  11.0  12.0
e  5.0  6.0  13.0  14.0