## 10월 27일 금요일 연습문제 : TF-IDF 기반 영화 추천시스템

- 데이터셋 : movies_metadata.csv에서 "영화 5000편"
- 동작 방식 : 사용자가 영화 제목을 입력하면, 해당 제목과 "overview" 기준 가장 유사한 10개의 영화를 추천

---------
즐겁게 봤던 영화 제목을 입력하세요 :
Toy Story
당신에게 추천하고 싶은 영화 제목은 아래와 같습니다.
1)
2)
...
10)
---------

<개발 방법>
1) overview 열 추출 > 단어 전처리(불용어 제거, 표제어(혹은 어간) 추출, 대소문자 통일, 특수문자 제거, 단어 통일(wordnet) 등) >  코퍼스 구성 (정규식 활용 가능)
2) TF-IDF 행렬 만들기
3) 코사인 유사도를 이용한 영화 추천

In [100]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from nltk.tokenize import word_tokenize
from nltk.tokenize import WordPunctTokenizer
from tensorflow.keras.preprocessing.text import text_to_word_sequence

In [101]:
data=pd.read_csv('archive/movies_metadata.csv')
data=data.head(5000)
data

C:\Users\user\AppData\Local\Temp\ipykernel_11012\3117426312.py:1: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  data=pd.read_csv('archive/movies_metadata.csv')


adult                              belongs_to_collection    budget  \
0     False  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000   
1     False                                                NaN  65000000   
2     False  {'id': 119050, 'name': 'Grumpy Old Men Collect...         0   
3     False                                                NaN  16000000   
4     False  {'id': 96871, 'name': 'Father of the Bride Col...         0   
...     ...                                                ...       ...   
4995  False                                                NaN         0   
4996  False                                                NaN  60000000   
4997  False  {'id': 217704, 'name': 'The Vampire Chronicles...  35000000   
4998  False                                                NaN         0   
4999  False                                                NaN         0   

                                                 genres  \
0     [{'id': 16, 'name': 'Animation'}, {'id': 35, '...   
1     [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...   
2     [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...   
3     [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   
4                        [{'id': 35, 'name': 'Comedy'}]   
...                                                 ...   
4995  [{'id': 53, 'name': 'Thriller'}, {'id': 27, 'n...   
4996                      [{'id': 18, 'name': 'Drama'}]   
4997  [{'id': 18, 'name': 'Drama'}, {'id': 14, 'name...   
4998  [{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...   
4999  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...   

                                  homepage     id    imdb_id  \
0     http://toystory.disney.com/toy-story    862  tt0114709   
1                                      NaN   8844  tt0113497   
2                                      NaN  15602  tt0113228   
3                                      NaN  31357  tt0114885   
4                                      NaN  11862  tt0113041   
...                                    ...    ...        ...   
4995                                   NaN  43715  tt0050294   
4996                                   NaN  10052  tt0259288   
4997                                   NaN  11979  tt0238546   
4998                                   NaN  75151  tt0260746   
4999                                   NaN  35868  tt0229002   

     original_language               original_title  \
0                   en                    Toy Story   
1                   en                      Jumanji   
2                   en             Grumpier Old Men   
3                   en            Waiting to Exhale   
4                   en  Father of the Bride Part II   
...                ...                          ...   
4995                en            The Deadly Mantis   
4996                en                    Dragonfly   
4997                en          Queen of the Damned   
4998                en                 Big Bad Love   
4999                en                 Green Dragon   

                                               overview  ... release_date  \
0     Led by Woody, Andy's toys live happily in his ...  ...   1995-10-30   
1     When siblings Judy and Peter discover an encha...  ...   1995-12-15   
2     A family wedding reignites the ancient feud be...  ...   1995-12-22   
3     Cheated on, mistreated and stepped on, the wom...  ...   1995-12-22   
4     Just when George Banks has recovered from his ...  ...   1995-02-10   
...                                                 ...  ...          ...   
4995  The calving of an Arctic iceberg releases a gi...  ...   1957-05-01   
4996  A grieving doctor is being contacted by his la...  ...   2002-02-22   
4997  Lestat de Lioncourt is awakened from his slumb...  ...   2002-02-10   
4998  Vietnam veteran Leon Barlow is struggling as a...  ...   2001-10-11   
4999  A tale about Vietnamese refugees sent to an or...  ...   2001-01-01   

          revenue runtime    

In [102]:
data=data[['original_title', 'overview']]
data

original_title  \
0                       Toy Story   
1                         Jumanji   
2                Grumpier Old Men   
3               Waiting to Exhale   
4     Father of the Bride Part II   
...                           ...   
4995            The Deadly Mantis   
4996                    Dragonfly   
4997          Queen of the Damned   
4998                 Big Bad Love   
4999                 Green Dragon   

                                               overview  
0     Led by Woody, Andy's toys live happily in his ...  
1     When siblings Judy and Peter discover an encha...  
2     A family wedding reignites the ancient feud be...  
3     Cheated on, mistreated and stepped on, the wom...  
4     Just when George Banks has recovered from his ...  
...                                                 ...  
4995  The calving of an Arctic iceberg releases a gi...  
4996  A grieving doctor is being contacted by his la...  
4997  Lestat de Lioncourt is awakened from his slumb...  
4998  Vietnam veteran Leon Barlow is struggling as a...  
4999  A tale about Vietnamese refugees sent to an or...  

[5000 rows x 2 columns]

In [103]:
overviews=data.overview
overviews

0       Led by Woody, Andy's toys live happily in his ...
1       When siblings Judy and Peter discover an encha...
2       A family wedding reignites the ancient feud be...
3       Cheated on, mistreated and stepped on, the wom...
4       Just when George Banks has recovered from his ...
                              ...                        
4995    The calving of an Arctic iceberg releases a gi...
4996    A grieving doctor is being contacted by his la...
4997    Lestat de Lioncourt is awakened from his slumb...
4998    Vietnam veteran Leon Barlow is struggling as a...
4999    A tale about Vietnamese refugees sent to an or...
Name: overview, Length: 5000, dtype: object

In [104]:
overview=overviews[0]
overview

"Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences."

In [105]:
import re

shortword = re.compile(r'\W*\b\w{1,2}\b')
overview = shortword.sub('', overview)
print(overview)

Led Woody, Andy toys live happily his room until Andy birthday brings Buzz Lightyear onto the scene. Afraid losing his place Andy heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns put aside their differences.


In [106]:
words=text_to_word_sequence(overview)
words

['led',
 'woody',
 'andy',
 'toys',
 'live',
 'happily',
 'his',
 'room',
 'until',
 'andy',
 'birthday',
 'brings',
 'buzz',
 'lightyear',
 'onto',
 'the',
 'scene',
 'afraid',
 'losing',
 'his',
 'place',
 'andy',
 'heart',
 'woody',
 'plots',
 'against',
 'buzz',
 'but',
 'when',
 'circumstances',
 'separate',
 'buzz',
 'and',
 'woody',
 'from',
 'their',
 'owner',
 'the',
 'duo',
 'eventually',
 'learns',
 'put',
 'aside',
 'their',
 'differences']

In [107]:
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()
words=[lemmatizer.lemmatize(word) for word in words]
words

['led',
 'woody',
 'andy',
 'toy',
 'live',
 'happily',
 'his',
 'room',
 'until',
 'andy',
 'birthday',
 'brings',
 'buzz',
 'lightyear',
 'onto',
 'the',
 'scene',
 'afraid',
 'losing',
 'his',
 'place',
 'andy',
 'heart',
 'woody',
 'plot',
 'against',
 'buzz',
 'but',
 'when',
 'circumstance',
 'separate',
 'buzz',
 'and',
 'woody',
 'from',
 'their',
 'owner',
 'the',
 'duo',
 'eventually',
 'learns',
 'put',
 'aside',
 'their',
 'difference']

In [108]:
shortword = re.compile(r'\W*\b\w{1,2}\b')
result = []

for overview in overviews:
    overview_s = shortword.sub('', str(overview))
    words = text_to_word_sequence(overview_s)
    words_final = [lemmatizer.lemmatize(word) for word in words]
    result.append(words_final)
    
result

[['led',
  'woody',
  'andy',
  'toy',
  'live',
  'happily',
  'his',
  'room',
  'until',
  'andy',
  'birthday',
  'brings',
  'buzz',
  'lightyear',
  'onto',
  'the',
  'scene',
  'afraid',
  'losing',
  'his',
  'place',
  'andy',
  'heart',
  'woody',
  'plot',
  'against',
  'buzz',
  'but',
  'when',
  'circumstance',
  'separate',
  'buzz',
  'and',
  'woody',
  'from',
  'their',
  'owner',
  'the',
  'duo',
  'eventually',
  'learns',
  'put',
  'aside',
  'their',
  'difference'],
 ['when',
  'sibling',
  'judy',
  'and',
  'peter',
  'discover',
  'enchanted',
  'board',
  'game',
  'that',
  'open',
  'the',
  'door',
  'magical',
  'world',
  'they',
  'unwittingly',
  'invite',
  'alan',
  'adult',
  'who',
  'been',
  'trapped',
  'inside',
  'the',
  'game',
  'for',
  'year',
  'into',
  'their',
  'living',
  'room',
  'alan',
  'only',
  'hope',
  'for',
  'freedom',
  'finish',
  'the',
  'game',
  'which',
  'prof',
  'risky',
  'all',
  'three',
  'find',
  'th

In [109]:
shortword = re.compile(r'\W*\b\w{1,2}\b')
lemmatizer = WordNetLemmatizer()

for index, overview in enumerate(data['overview']):
    overview_s = shortword.sub('', str(overview))
    words = text_to_word_sequence(overview_s)
    words_final = [lemmatizer.lemmatize(word) for word in words]
    data.at[index, 'overview'] = ' '.join(words_final)

In [110]:
data

original_title  \
0                       Toy Story   
1                         Jumanji   
2                Grumpier Old Men   
3               Waiting to Exhale   
4     Father of the Bride Part II   
...                           ...   
4995            The Deadly Mantis   
4996                    Dragonfly   
4997          Queen of the Damned   
4998                 Big Bad Love   
4999                 Green Dragon   

                                               overview  
0     led woody andy toy live happily his room until...  
1     when sibling judy and peter discover enchanted...  
2     family wedding reignites the ancient feud betw...  
3     cheated mistreated and stepped the woman are h...  
4     just when george bank ha recovered from his da...  
...                                                 ...  
4995  the calving arctic iceberg release giant prayi...  
4996  grieving doctor being contacted his late wife ...  
4997  lestat lioncourt awakened from his slumber bor...  
4998  vietnam veteran leon barlow struggling writer ...  
4999  tale about vietnamese refugee sent orientation...  

[5000 rows x 2 columns]

In [111]:
data.overview[0]

'led woody andy toy live happily his room until andy birthday brings buzz lightyear onto the scene afraid losing his place andy heart woody plot against buzz but when circumstance separate buzz and woody from their owner the duo eventually learns put aside their difference'

In [112]:
tfidf=TfidfVectorizer()

In [113]:
tfidf_mat=tfidf.fit_transform(data['overview'])

In [114]:
tfidf_mat

<5000x20240 sparse matrix of type '<class 'numpy.float64'>'
	with 183341 stored elements in Compressed Sparse Row format>

In [115]:
tfidf_mat.toarray()[0]

array([0., 0., 0., ..., 0., 0., 0.])

In [116]:
tfidf.vocabulary_

{'led': 10503,
 'woody': 19984,
 'andy': 902,
 'toy': 18475,
 'live': 10754,
 'happily': 8206,
 'his': 8570,
 'room': 15519,
 'until': 19080,
 'birthday': 2052,
 'brings': 2509,
 'buzz': 2730,
 'lightyear': 10661,
 'onto': 12874,
 'the': 18148,
 'scene': 15895,
 'afraid': 563,
 'losing': 10879,
 'place': 13731,
 'heart': 8361,
 'plot': 13796,
 'against': 578,
 'but': 2714,
 'when': 19766,
 'circumstance': 3416,
 'separate': 16155,
 'and': 882,
 'from': 7293,
 'their': 18154,
 'owner': 13130,
 'duo': 5698,
 'eventually': 6327,
 'learns': 10487,
 'put': 14429,
 'aside': 1236,
 'difference': 5103,
 'sibling': 16466,
 'judy': 9874,
 'peter': 13561,
 'discover': 5216,
 'enchanted': 6041,
 'board': 2190,
 'game': 7425,
 'that': 18140,
 'open': 12879,
 'door': 5471,
 'magical': 11080,
 'world': 20004,
 'they': 18181,
 'unwittingly': 19099,
 'invite': 9520,
 'alan': 656,
 'adult': 502,
 'who': 19810,
 'been': 1807,
 'trapped': 18559,
 'inside': 9330,
 'for': 7086,
 'year': 20115,
 'into': 9464

In [117]:
tfidf.get_feature_names_out()

array(['000', '007', '05pm', ..., 'zyto', 'émigré', 'état'], dtype=object)

In [118]:
tfidf_df=pd.DataFrame(tfidf_mat.toarray(), columns=tfidf.get_feature_names_out())
tfidf_df

000  007  05pm  100  101  103  10th  114  1183  11th  ...  zords  zorin  \
0     0.0  0.0   0.0  0.0  0.0  0.0   0.0  0.0   0.0   0.0  ...    0.0    0.0   
1     0.0  0.0   0.0  0.0  0.0  0.0   0.0  0.0   0.0   0.0  ...    0.0    0.0   
2     0.0  0.0   0.0  0.0  0.0  0.0   0.0  0.0   0.0   0.0  ...    0.0    0.0   
3     0.0  0.0   0.0  0.0  0.0  0.0   0.0  0.0   0.0   0.0  ...    0.0    0.0   
4     0.0  0.0   0.0  0.0  0.0  0.0   0.0  0.0   0.0   0.0  ...    0.0    0.0   
...   ...  ...   ...  ...  ...  ...   ...  ...   ...   ...  ...    ...    ...   
4995  0.0  0.0   0.0  0.0  0.0  0.0   0.0  0.0   0.0   0.0  ...    0.0    0.0   
4996  0.0  0.0   0.0  0.0  0.0  0.0   0.0  0.0   0.0   0.0  ...    0.0    0.0   
4997  0.0  0.0   0.0  0.0  0.0  0.0   0.0  0.0   0.0   0.0  ...    0.0    0.0   
4998  0.0  0.0   0.0  0.0  0.0  0.0   0.0  0.0   0.0   0.0  ...    0.0    0.0   
4999  0.0  0.0   0.0  0.0  0.0  0.0   0.0  0.0   0.0   0.0  ...    0.0    0.0   

      zorro  zubin  zuckermann  zula  zulu  zyto  émigré  état  
0       0.0    0.0         0.0   0.0   0.0   0.0     0.0   0.0  
1       0.0    0.0         0.0   0.0   0.0   0.0     0.0   0.0  
2       0.0    0.0         0.0   0.0   0.0   0.0     0.0   0.0  
3       0.0    0.0         0.0   0.0   0.0   0.0     0.0   0.0  
4       0.0    0.0         0.0   0.0   0.0   0.0     0.0   0.0  
...     ...    ...         ...   ...   ...   ...     ...   ...  
4995    0.0    0.0         0.0   0.0   0.0   0.0     0.0   0.0  
4996    0.0    0.0         0.0   0.0   0.0   0.0     0.0   0.0  
4997    0.0    0.0         0.0   0.0   0.0   0.0     0.0   0.0  
4998    0.0    0.0         0.0   0.0   0.0   0.0     0.0   0.0  
4999    0.0    0.0         0.0   0.0   0.0   0.0     0.0   0.0  

[5000 rows x 20240 columns]

In [135]:
cs=cosine_similarity(tfidf_df)
cs

array([[1.        , 0.03425493, 0.01012865, ..., 0.02340008, 0.03019161,
        0.00996605],
       [0.03425493, 1.        , 0.0542086 , ..., 0.03500056, 0.00875896,
        0.02331573],
       [0.01012865, 0.0542086 , 1.        , ..., 0.03529602, 0.00962463,
        0.02168051],
       ...,
       [0.02340008, 0.03500056, 0.03529602, ..., 1.        , 0.06262757,
        0.0346923 ],
       [0.03019161, 0.00875896, 0.00962463, ..., 0.06262757, 1.        ,
        0.03874545],
       [0.00996605, 0.02331573, 0.02168051, ..., 0.0346923 , 0.03874545,
        1.        ]])

In [136]:
cs.shape

(5000, 5000)

In [137]:
cs[0]

array([1.        , 0.03425493, 0.01012865, ..., 0.02340008, 0.03019161,
       0.00996605])

In [148]:
cs[0].argsort()[-11:][:10]

array([1884, 3252, 2157, 4078,  485,  448, 1932, 3057, 1071, 2997],
      dtype=int64)

In [126]:
data['original_title'].iloc[[1884, 3252, 2157, 4078,  485,  448, 1932, 3057, 1071, 2997]]

1884           Child's Play 3
3252          Bound for Glory
2157        Indecent Proposal
4078                Losin' It
485                    Malice
448         For Love or Money
1932                Condorman
3057          Man on the Moon
1071    Rebel Without a Cause
2997              Toy Story 2
Name: original_title, dtype: object

In [151]:
movie_title = input('영화 제목 :')

movie_index = data[data['original_title']==movie_title].index[0]

movie = cs[movie_index].argsort()[-11:][:10]

data['original_title'].iloc[movie]

영화 제목 :Jumanji


1951                    BASEketball
4823    The People That Time Forgot
363                        Maverick
3056               Any Given Sunday
696                    Celtic Pride
3872             Dungeons & Dragons
4652          Sidewalks of New York
2056       Your Friends & Neighbors
2486                       eXistenZ
1506             The Innocent Sleep
Name: original_title, dtype: object